apiVersion: v1
kind: Service
metadata:
    name: spring-boot-k8s-xm-svc
spec:
    selector:
        app: spring-boot-k8s-xm
    ports:
        -   protocol: "TCP"
            port: 8080
            targetPort: 8090
    type: NodePort
