server:
    port: 8090
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false

spring:
    application:
        name: XM
    datasource:
        url: jdbc:postgresql://localhost:55000/xm
        username: postgres
        password: postgrespw
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                hbm2ddl:
                    auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    servlet:
        multipart:
            max-file-size: 1MB # protection for not uploading too big files and kill service
            max-request-size: 1MB
logging:
    level:
        org:
            zalando:
                logbook:
                    Logbook: TRACE


