server:
    port: 8090
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false

spring:
    data:
        rest:
            detection-strategy: annotated
    application:
        name: XM
    datasource:
        url: jdbc:h2:mem:test
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                hbm2ddl:
                    auto: update # Hibernate ddl auto (create, create-drop, validate, update)
    servlet:
        multipart:
            max-file-size: 1MB # protection for not uploading too big files and kill service
            max-request-size: 1MB
logging:
    level:
        org:
            zalando:
                logbook:
                    Logbook: TRACE


